export const AVATAR_ONLINE_PUSH = "AVATAR_ONLINE_PUSH";
export const AVATAR_ONLINE_LOGIN_UPDATE = "AVATAR_ONLINE_LOGIN_UPDATE";
export const AVATAR_ONLINE_LOGOUT_UPDATE = "AVATAR_ONLINE_LOGOUT_UPDATE";
