export const MESSAGE_GET_NOTSEEN_COUNT_REQUEST =
  "MESSAGE_GET_NOTSEEN_COUNT_REQUEST";
export const MESSAGE_GET_NOTSEEN_COUNT_SUCCESS =
  "MESSAGE_GET_NOTSEEN_COUNT_SUCCESS";
export const MESSAGE_GET_NOTSEEN_COUNT_FAIL = "MESSAGE_GET_NOTSEEN_COUNT_FAIL";
export const MESSAGE_GET_NOTSEEN_COUNT_RESET =
  "MESSAGE_GET_NOTSEEN_COUNT_RESET";

export const MESSAGE_GET_CONVERTATIONS_REQUEST =
  "MESSAGE_GET_CONVERTATIONS_REQUEST";
export const MESSAGE_GET_CONVERTATIONS_SUCCESS =
  "MESSAGE_GET_CONVERTATIONS_SUCCESS";
export const MESSAGE_GET_CONVERTATIONS_FAIL = "MESSAGE_GET_CONVERTATIONS_FAIL";
export const MESSAGE_GET_CONVERTATIONS_RESET =
  "MESSAGE_GET_CONVERTATIONS_RESET";

export const MESSAGE_GET_LIST_REQUEST = "MESSAGE_GET_LIST_REQUEST";
export const MESSAGE_GET_LIST_SUCCESS = "MESSAGE_GET_LIST_SUCCESS";
export const MESSAGE_GET_LIST_FAIL = "MESSAGE_GET_LIST_FAIL";
export const MESSAGE_GET_LIST_RESET = "MESSAGE_GET_LIST_RESET";
