export const MESSAGE_GET_NOTSEEN_COUNT_REQUEST =
  "MESSAGE_GET_NOTSEEN_COUNT_REQUEST";
export const MESSAGE_GET_NOTSEEN_COUNT_SUCCESS =
  "MESSAGE_GET_NOTSEEN_COUNT_SUCCESS";
export const MESSAGE_GET_NOTSEEN_COUNT_FAIL = "MESSAGE_GET_NOTSEEN_COUNT_FAIL";
export const MESSAGE_GET_NOTSEEN_COUNT_RESET =
  "MESSAGE_GET_NOTSEEN_COUNT_RESET";
export const MESSAGE_GET_NOTSEEN_COUNT_UPDATE =
  "MESSAGE_GET_NOTSEEN_COUNT_UPDATE";

export const MESSAGE_GET_CONVERTATIONS_REQUEST =
  "MESSAGE_GET_CONVERTATIONS_REQUEST";
export const MESSAGE_GET_CONVERTATIONS_SUCCESS =
  "MESSAGE_GET_CONVERTATIONS_SUCCESS";
export const MESSAGE_GET_CONVERTATIONS_FAIL = "MESSAGE_GET_CONVERTATIONS_FAIL";
export const MESSAGE_GET_CONVERTATIONS_RESET =
  "MESSAGE_GET_CONVERTATIONS_RESET";
export const MESSAGE_GET_CONVERTATIONS_UPDATE_MESSAGE =
  "MESSAGE_GET_CONVERTATIONS_UPDATE_MESSAGE";
export const MESSAGE_GET_CONVERTATIONS_UPDATE_REMOVE_CONV =
  "MESSAGE_GET_CONVERTATIONS_UPDATE_REMOVE_CONV";
export const MESSAGE_GET_CONVERTATIONS_UPDATE_REMOVE_MESSAGE =
  "MESSAGE_GET_CONVERTATIONS_UPDATE_REMOVE_MESSAGE";
export const MESSAGE_GET_CONVERTATIONS_UPDATE_SEEN_ALL =
  "MESSAGE_GET_CONVERTATIONS_UPDATE_SEEN_ALL";
export const MESSAGE_GET_CONVERTATIONS_UPDATE_USER_TYPING =
  "MESSAGE_GET_CONVERTATIONS_UPDATE_USER_TYPING";
export const MESSAGE_GET_CONVERTATIONS_UPDATE_USER_STOP_TYPING =
  "MESSAGE_GET_CONVERTATIONS_UPDATE_USER_STOP_TYPING";

export const MESSAGE_GET_LIST_REQUEST = "MESSAGE_GET_LIST_REQUEST";
export const MESSAGE_GET_LIST_SUCCESS = "MESSAGE_GET_LIST_SUCCESS";
export const MESSAGE_GET_LIST_FAIL = "MESSAGE_GET_LIST_FAIL";
export const MESSAGE_GET_LIST_RESET = "MESSAGE_GET_LIST_RESET";
export const MESSAGE_GET_LIST_UPDATE_PUSH = "MESSAGE_GET_LIST_UPDATE_PUSH";
export const MESSAGE_GET_LIST_UPDATE_REMOVE = "MESSAGE_GET_LIST_UPDATE_REMOVE";
export const MESSAGE_GET_LIST_UPDATE_SEEN_ALL =
  "MESSAGE_GET_LIST_UPDATE_SEEN_ALL";

export const MESSAGE_SEND_REQUEST = "MESSAGE_SEND_REQUEST";
export const MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS";
export const MESSAGE_SEND_FAIL = "MESSAGE_SEND_FAIL";
export const MESSAGE_SEND_RESET = "MESSAGE_SEND_RESET";

export const MESSAGE_DELETE_REQUEST = "MESSAGE_DELETE_REQUEST";
export const MESSAGE_DELETE_SUCCESS = "MESSAGE_DELETE_SUCCESS";
export const MESSAGE_DELETE_FAIL = "MESSAGE_DELETE_FAIL";
export const MESSAGE_DELETE_RESET = "MESSAGE_DELETE_RESET";

export const MESSAGE_REMOVE_CONVERTATION_REQUEST =
  "MESSAGE_REMOVE_CONVERTATION_REQUEST";
export const MESSAGE_REMOVE_CONVERTATION_SUCCESS =
  "MESSAGE_REMOVE_CONVERTATION_SUCCESS";
export const MESSAGE_REMOVE_CONVERTATION_FAIL =
  "MESSAGE_REMOVE_CONVERTATION_FAIL";
export const MESSAGE_REMOVE_CONVERTATION_RESET =
  "MESSAGE_REMOVE_CONVERTATION_RESET";

export const MESSAGE_SEEN_ALL_REQUEST = "MESSAGE_SEEN_ALL_REQUEST";
export const MESSAGE_SEEN_ALL_SUCCESS = "MESSAGE_SEEN_ALL_SUCCESS";
export const MESSAGE_SEEN_ALL_FAIL = "MESSAGE_SEEN_ALL_FAIL";
export const MESSAGE_SEEN_ALL_RESET = "MESSAGE_SEEN_ALL_RESET";

export const MESSAGE_GET_NOTSEEN_REQUEST = "MESSAGE_GET_NOTSEEN_REQUEST";
export const MESSAGE_GET_NOTSEEN_SUCCESS = "MESSAGE_GET_NOTSEEN_SUCCESS";
export const MESSAGE_GET_NOTSEEN_FAIL = "MESSAGE_GET_NOTSEEN_FAIL";
export const MESSAGE_GET_NOTSEEN_RESET = "MESSAGE_GET_NOTSEEN_RESET";
export const MESSAGE_GET_NOTSEEN_UPDATE_PUSH =
  "MESSAGE_GET_NOTSEEN_UPDATE_PUSH";

export const MESSAGE_SEEN_TOAST_REQUEST = "MESSAGE_SEEN_TOAST_REQUEST";
export const MESSAGE_SEEN_TOAST_SUCCESS = "MESSAGE_SEEN_TOAST_SUCCESS";
export const MESSAGE_SEEN_TOAST_FAIL = "MESSAGE_SEEN_TOAST_FAIL";
export const MESSAGE_SEEN_TOAST_RESET = "MESSAGE_SEEN_TOAST_RESET";
