export const CONVERTATION_OPEN = "CONVERTATION_OPEN";
export const CONVERTATION_CLOSE = "CONVERTATION_CLOSE";
export const CONVERTATION_UPDATE_SET_ONLINE = "CONVERTATION_UPDATE_SET_ONLINE";
export const CONVERTATION_UPDATE_SET_OFFLINE =
  "CONVERTATION_UPDATE_SET_OFFLINE";
export const CONVERTATION_UPDATE_SET_DATE_DIFF_INC =
  "CONVERTATION_UPDATE_SET_DATE_DIFF_INC";
