export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";
export const POST_LIST_RESET = "POST_LIST_RESET";
export const POST_LIST_UPDATE_ADD_POST = "POST_LIST_UPDATE_ADD_POST";
export const POST_LIST_UPDATE_LIKE = "POST_LIST_UPDATE_LIKE";
export const POST_LIST_UPDATE_UNLIKE = "POST_LIST_UPDATE_UNLIKE";
export const POST_LIST_UPDATE_DELETE_POST = "POST_LIST_UPDATE_DELETE_POST";
export const POST_GET_LIST_UPDATE_COMMENT = "POST_GET_LIST_UPDATE_COMMENT";
export const POST_GET_LIST_UPDATE_DELETE_COMMENT =
  "POST_GET_LIST_UPDATE_DELETE_COMMENT";

export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";
export const POST_CREATE_RESET = "POST_CREATE_RESET";

export const POST_GET_BY_ID_REQUEST = "POST_GET_BY_ID_REQUEST";
export const POST_GET_BY_ID_SUCCESS = "POST_GET_BY_ID_SUCCESS";
export const POST_GET_BY_ID_FAIL = "POST_GET_BY_ID_FAIL";
export const POST_GET_BY_ID_RESET = "POST_GET_BY_ID_RESET";
export const POST_GET_BY_ID_UPDATE_COMMENT = "POST_GET_BY_ID_UPDATE_COMMENT";
export const POST_GET_BY_ID_UPDATE_DELETE_COMMENT =
  "POST_GET_BY_ID_UPDATE_DELETE_COMMENT";

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";
export const POST_DELETE_RESET = "POST_DELETE_RESET";

export const POST_LIKE_REQUEST = "POST_LIKE_REQUEST";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";
export const POST_LIKE_FAIL = "POST_LIKE_FAIL";
export const POST_LIKE_RESET = "POST_LIKE_RESET";

export const POST_UNLIKE_REQUEST = "POST_UNLIKE_REQUEST";
export const POST_UNLIKE_SUCCESS = "POST_UNLIKE_SUCCESS";
export const POST_UNLIKE_FAIL = "POST_UNLIKE_FAIL";
export const POST_UNLIKE_RESET = "POST_UNLIKE_RESET";

export const POST_ADD_COMMENT_REQUEST = "POST_ADD_COMMENT_REQUEST";
export const POST_ADD_COMMENT_SUCCESS = "POST_ADD_COMMENT_SUCCESS";
export const POST_ADD_COMMENT_FAIL = "POST_ADD_COMMENT_FAIL";
export const POST_ADD_COMMENT_RESET = "POST_ADD_COMMENT_RESET";

export const POST_DELETE_COMMENT_REQUEST = "POST_DELETE_COMMENT_REQUEST";
export const POST_DELETE_COMMENT_SUCCESS = "POST_DELETE_COMMENT_SUCCESS";
export const POST_DELETE_COMMENT_FAIL = "POST_DELETE_COMMENT_FAIL";
export const POST_DELETE_COMMENT_RESET = "POST_DELETE_COMMENT_RESET";
