export const NOTIFICATION_SEND_REQUEST = "NOTIFICATION_SEND_REQUEST";
export const NOTIFICATION_SEND_SUCCESS = "NOTIFICATION_SEND_SUCCESS";
export const NOTIFICATION_SEND_FAIL = "NOTIFICATION_SEND_FAIL";
export const NOTIFICATION_SEND_RESET = "NOTIFICATION_SEND_RESET";

export const NOTIFICATION_GET_LIST_REQUEST = "NOTIFICATION_GET_LIST_REQUEST";
export const NOTIFICATION_GET_LIST_SUCCESS = "NOTIFICATION_GET_LIST_SUCCESS";
export const NOTIFICATION_GET_LIST_FAIL = "NOTIFICATION_GET_LIST_FAIL";
export const NOTIFICATION_GET_LIST_RESET = "NOTIFICATION_SEND_RESET";
export const NOTIFICATION_GET_LIST_SEEN_UPDATE =
  "NOTIFICATION_GET_LIST_SEEN_UPDATE";
export const NOTIFICATION_GET_LIST_DELETE_UPDATE =
  "NOTIFICATION_GET_LIST_DELETE_UPDATE";

export const NOTIFICATION_DELETE_REQUEST = "NOTIFICATION_DELETE_REQUEST";
export const NOTIFICATION_DELETE_SUCCESS = "NOTIFICATION_DELETE_SUCCESS";
export const NOTIFICATION_DELETE_FAIL = "NOTIFICATION_DELETE_FAIL";
export const NOTIFICATION_DELETE_RESET = "NOTIFICATION_SEND_RESET";

export const NOTIFICATION_SEEN_ALL_REQUEST = "NOTIFICATION_SEEN_ALL_REQUEST";
export const NOTIFICATION_SEEN_ALL_SUCCESS = "NOTIFICATION_SEEN_ALL_SUCCESS";
export const NOTIFICATION_SEEN_ALL_FAIL = "NOTIFICATION_SEEN_ALL_FAIL";
export const NOTIFICATION_SEEN_ALL_RESET = "NOTIFICATION_SEND_RESET";
