export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_GET_BY_ID_REQUEST = "USER_GET_BY_ID_REQUEST";
export const USER_GET_BY_ID_SUCCESS = "USER_GET_BY_ID_SUCCESS";
export const USER_GET_BY_ID_FAIL = "USER_GET_BY_ID_FAIL";
export const USER_GET_BY_ID_RESET = "USER_GET_BY_ID_RESET";
export const USER_GET_BY_ID_UPDATE_FOLLOW = "USER_GET_BY_ID_UPDATE_FOLLOW";
// export const USER_GET_BY_ID_UPDATE_UNFOLLOW = "USER_GET_BY_ID_UPDATE_UNFOLLOW";
// export const USER_GET_BY_ID_UPDATE_REMOVE = "USER_GET_BY_ID_UPDATE_REMOVE";

export const USER_CHANGE_NAME_REQUEST = "USER_CHANGE_NAME_REQUEST";
export const USER_CHANGE_NAME_SUCCESS = "USER_CHANGE_NAME_SUCCESS";
export const USER_CHANGE_NAME_FAIL = "USER_CHANGE_NAME_FAIL";
export const USER_CHANGE_NAME_RESET = "USER_CHANGE_NAME_RESET";

export const USER_CHANGE_PASSWORD_REQUEST = "USER_CHANGE_PASSWORD_REQUEST";
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS";
export const USER_CHANGE_PASSWORD_FAIL = "USER_CHANGE_PASSWORD_FAIL";
export const USER_CHANGE_PASSWORD_RESET = "USER_CHANGE_PASSWORD_RESET";

export const USER_CHANGE_AVATAR_REQUEST = "USER_CHANGE_AVATAR_REQUEST";
export const USER_CHANGE_AVATAR_SUCCESS = "USER_CHANGE_AVATAR_SUCCESS";
export const USER_CHANGE_AVATAR_FAIL = "USER_CHANGE_AVATAR_FAIL";
export const USER_CHANGE_AVATAR_RESET = "USER_CHANGE_AVATAR_RESET";

export const USER_CHANGE_ACCOUNT_STATE_REQUEST =
  "USER_CHANGE_ACCOUNT_STATE_REQUEST";
export const USER_CHANGE_ACCOUNT_STATE_SUCCESS =
  "USER_CHANGE_ACCOUNT_STATE_SUCCESS";
export const USER_CHANGE_ACCOUNT_STATE_FAIL = "USER_CHANGE_ACCOUNT_STATE_FAIL";
export const USER_CHANGE_ACCOUNT_STATE_RESET =
  "USER_CHANGE_ACCOUNT_STATE_RESET";

export const USER_FIND_REQUEST = "USER_FIND_REQUEST";
export const USER_FIND_SUCCESS = "USER_FIND_SUCCESS";
export const USER_FIND_FAIL = "USER_FIND_FAIL";
export const USER_FIND_RESET = "USER_FIND_RESET";
// export const USER_FIND_UPDATE_FOLLOW = "USER_FIND_UPDATE_FOLLOW";
// export const USER_FIND_UPDATE_UNFOLLOW = "USER_FIND_UPDATE_UNFOLLOW";

export const USER_GET_REQUESTS_REQUEST = "USER_GET_REQUESTS_REQUEST";
export const USER_GET_REQUESTS_SUCCESS = "USER_GET_REQUESTS_SUCCESS";
export const USER_GET_REQUESTS_FAIL = "USER_GET_REQUESTS_FAIL";
export const USER_GET_REQUESTS_RESET = "USER_GET_REQUESTS_RESET";
export const USER_GET_REQUESTS_UPDATE_REMOVE =
  "USER_GET_REQUESTS_UPDATE_REMOVE";

export const USER_FOLLOW_REQUEST = "USER_FOLLOW_REQUEST";
export const USER_FOLLOW_SUCCESS = "USER_FOLLOW_SUCCESS";
export const USER_FOLLOW_FAIL = "USER_FOLLOW_FAIL";
export const USER_FOLLOW_RESET = "USER_FOLLOW_RESET";

export const USER_CHECK_FOLLOW_REQUEST = "USER_CHECK_FOLLOW_REQUEST";
export const USER_CHECK_FOLLOW_SUCCESS = "USER_CHECK_FOLLOW_SUCCESS";
export const USER_CHECK_FOLLOW_FAIL = "USER_CHECK_FOLLOW_FAIL";
export const USER_CHECK_FOLLOW_RESET = "USER_CHECK_FOLLOW_RESET";
export const USER_CHECK_FOLLOW_UPDATE_REMOVE =
  "USER_CHECK_FOLLOW_UPDATE_REMOVE";

export const USER_ACCEPT_FOLLOW_REQUEST = "USER_ACCEPT_FOLLOW_REQUEST";
export const USER_ACCEPT_FOLLOW_SUCCESS = "USER_ACCEPT_FOLLOW_SUCCESS";
export const USER_ACCEPT_FOLLOW_FAIL = "USER_ACCEPT_FOLLOW_FAIL";
export const USER_ACCEPT_FOLLOW_RESET = "USER_ACCEPT_FOLLOW_RESET";

export const USER_REJECT_FOLLOW_REQUEST = "USER_REJECT_FOLLOW_REQUEST";
export const USER_REJECT_FOLLOW_SUCCESS = "USER_REJECT_FOLLOW_SUCCESS";
export const USER_REJECT_FOLLOW_FAIL = "USER_REJECT_FOLLOW_FAIL";
export const USER_REJECT_FOLLOW_RESET = "USER_REJECT_FOLLOW_RESET";

export const USER_UNFOLLOW_REQUEST = "USER_UNFOLLOW_REQUEST";
export const USER_UNFOLLOW_SUCCESS = "USER_UNFOLLOW_SUCCESS";
export const USER_UNFOLLOW_FAIL = "USER_UNFOLLOW_FAIL";
export const USER_UNFOLLOW_RESET = "USER_UNFOLLOW_RESET";

export const USER_REMOVE_FOLLOWING_REQUEST = "USER_REMOVE_FOLLOWING_REQUEST";
export const USER_REMOVE_FOLLOWING_SUCCESS = "USER_REMOVE_FOLLOWING_SUCCESS";
export const USER_REMOVE_FOLLOWING_FAIL = "USER_REMOVE_FOLLOWING_FAIL";
export const USER_REMOVE_FOLLOWING_RESET = "USER_REMOVE_FOLLOWING_RESET";

export const USER_GET_FOLLOWERS_REQUEST = "USER_GET_FOLLOWERS_REQUEST";
export const USER_GET_FOLLOWERS_SUCCESS = "USER_GET_FOLLOWERS_SUCCESS";
export const USER_GET_FOLLOWERS_FAIL = "USER_GET_FOLLOWERS_FAIL";
export const USER_GET_FOLLOWERS_RESET = "USER_GET_FOLLOWERS_RESET";
